import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync('v20/editor.js','utf8');
const layers=['a','b','c'].map(id=>({id,libraryLocked:true,x:12,y:34,scale:1.2}));
let snapshots=0,renders=0;
const context=vm.createContext({zoneState:()=>({layers}),snapshot:()=>snapshots++,renderAll:()=>renders++,activeLayerId:null});
vm.runInContext(source.slice(source.indexOf('function reorderLayer('),source.indexOf('function renderLayerPanel(')),context);
context.reorderLayer('a','b');
assert.deepEqual(layers.map(l=>l.id),['b','a','c']);
context.reorderLayer('a','c');
assert.deepEqual(layers.map(l=>l.id),['b','c','a']);
context.reorderLayer('a','b');
assert.deepEqual(layers.map(l=>l.id),['a','b','c']);
context.reorderLayer('a','a');context.reorderLayer('missing','a');
assert.equal(snapshots,3);assert.equal(renders,3);
assert.ok(layers.every(l=>l.libraryLocked&&l.x===12&&l.y===34&&l.scale===1.2));
assert.ok(!source.includes('orderLocked'));
assert.ok(!source.includes("$('statusProduct')"));
assert.ok(source.includes("$('layerControls')?.closest('.section')"));
assert.ok(!fs.readFileSync('index.html','utf8').includes('Design status'));
console.log('Layer order and sidebar checks passed');
