create table if not exists public.mqd_library_assets (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 1 and 120),
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  category text not null check (category in ('background','icon')),
  placement_mode text not null default 'locked' check (placement_mode in ('locked','editable')),
  master_path text not null unique,
  render_path text not null unique,
  active boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mqd_library_asset_placements (
  id bigint generated by default as identity primary key,
  asset_id uuid not null references public.mqd_library_assets(id) on delete cascade,
  product_id text not null check (char_length(product_id) between 1 and 100),
  zone_name text not null check (char_length(zone_name) between 1 and 100),
  x numeric(7,3) not null default 0 check (x between -100 and 100),
  y numeric(7,3) not null default 0 check (y between -100 and 100),
  scale numeric(7,4) not null default 1 check (scale between 0.05 and 4),
  rotation numeric(7,3) not null default 0 check (rotation between -180 and 180),
  flip_x boolean not null default false,
  flip_y boolean not null default false,
  crop jsonb not null default '{"left":0,"top":0,"right":0,"bottom":0}'::jsonb,
  created_at timestamptz not null default now(),
  unique(asset_id,product_id,zone_name)
);

alter table public.mqd_library_assets enable row level security;
alter table public.mqd_library_assets force row level security;
alter table public.mqd_library_asset_placements enable row level security;
alter table public.mqd_library_asset_placements force row level security;

revoke all on public.mqd_library_assets from anon, authenticated;
revoke all on public.mqd_library_asset_placements from anon, authenticated;

create index if not exists mqd_library_assets_active_sort_idx on public.mqd_library_assets(active,sort_order,name);
create index if not exists mqd_library_placements_context_idx on public.mqd_library_asset_placements(product_id,zone_name,asset_id);

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('mqd-library-assets','mqd-library-assets',false,52428800,array['image/png','image/jpeg','image/webp']::text[])
on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

-- No client Storage policies are created. Only service-role Edge Functions can
-- read the display derivatives or master artwork in this private bucket.
